name = "3d-scanner-backend"
main = "functions/index.js"
compatibility_date = "2024-01-01"

# D1 Database configuration
[[d1_databases]]
binding = "DB"
database_name = "3d-scanner-db"
database_id = "1cfdbeec-89f0-4ba6-a12b-d5c183310dba"

# R2 Bucket configuration (enable R2 in dashboard first)
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "3d-models-bucket"

# Environment variables
[vars]
ENVIRONMENT = "production"

# Production environment
[env.production]
name = "3d-scanner-backend-prod"
